import type { Narrative } from '../schemas/narrator.js';
import type { ReconciliationSession } from '../services/data.js';

const PURPLE = '#8E31B5';
const BLUE   = '#5793EC';
const GRADIENT = `linear-gradient(90deg, ${PURPLE}, ${BLUE})`;

function categoryBadge(category: 'vendor' | 'pattern' | 'risk'): string {
  const styles: Record<string, string> = {
    vendor:  `background:#f5eafa;color:${PURPLE};`,
    risk:    'background:#ffe8e8;color:#c0392b;',
    pattern: `background:#e8f2ff;color:${BLUE};`,
  };
  return `<span style="font-size:9px;text-transform:uppercase;letter-spacing:1px;font-weight:600;
    padding:3px 9px;border-radius:999px;white-space:nowrap;${styles[category]}">${category}</span>`;
}

function probabilityBar(pct: number): string {
  const width = Math.round(pct * 100);
  return `
    <div style="height:5px;background:#e8e4f0;border-radius:3px;margin:8px 0 0;">
      <div style="height:100%;width:${width}%;background:${GRADIENT};border-radius:3px;"></div>
    </div>`;
}

export function buildClosingReportHtml(
  narrator: Narrative,
  session: ReconciliationSession,
  generatedAt: string,
  generatedBy?: string,
): string {
  const currentPct = Math.round(narrator.stats.closeProbability * 100);
  const nextPct    = Math.round(narrator.nextCloseProbability * 100);
  const deltaSign  = narrator.nextCloseDelta >= 0 ? '+' : '';
  const matchRate  = Math.round(
    (narrator.stats.matched / (narrator.stats.matched + narrator.stats.unmatched)) * 100,
  );

  const insightsHtml = narrator.learnedThisSession
    .map(
      (item) => `
      <div style="display:flex;gap:12px;align-items:flex-start;padding:12px 0;border-bottom:1px solid #f0ecf5;">
        <div style="margin-top:2px;min-width:64px;">${categoryBadge(item.category)}</div>
        <p style="font-size:13px;line-height:1.75;color:#374151;flex:1;margin:0;">${item.insight}</p>
      </div>`,
    )
    .join('');

  const statsItems = [
    { label: 'Transactions Matched', value: String(narrator.stats.matched) },
    { label: 'Remaining Unmatched',  value: String(narrator.stats.unmatched) },
    { label: 'Match Rate',           value: `${matchRate}%` },
    { label: 'Blockers Resolved',    value: String(narrator.stats.resolvedBlockers) },
  ];

  const statsHtml = statsItems
    .map(
      (s, i) => `
      <div style="flex:1;padding:18px 20px;text-align:center;${i > 0 ? `border-left:1px solid #e8e4f0;` : ''}">
        <div style="font-size:26px;font-weight:700;color:#111827;font-family:'Mulish',sans-serif;">${s.value}</div>
        <div style="font-size:9px;text-transform:uppercase;letter-spacing:1.2px;color:#9ca3af;margin-top:5px;">${s.label}</div>
      </div>`,
    )
    .join('');

  const narrativeParagraphs = narrator.narrative
    .split('\n\n')
    .map(
      (para) =>
        `<p style="font-size:13.5px;line-height:1.85;color:#374151;margin:0 0 14px;">${para.trim()}</p>`,
    )
    .join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Mulish:wght@400;600;700;800&display=swap" rel="stylesheet">
  <style>
    * { margin:0; padding:0; box-sizing:border-box; }
    body {
      font-family: 'Mulish', system-ui, -apple-system, sans-serif;
      color: #111827;
      background: #ffffff;
      font-size: 14px;
    }
    .no-break { break-inside: avoid; page-break-inside: avoid; }
    @page { margin-top: 28px; }
    @page :first { margin-top: 0; }
  </style>
</head>
<body>

  <!-- ACCENT STRIP -->
  <div style="height:3px;width:100%;background:${PURPLE};"></div>

  <!-- HEADER -->
  <div style="background:#ffffff;padding:20px 48px;display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid #e5e7eb;">
    <div>
      <span style="font-size:20px;font-weight:800;color:${PURPLE};letter-spacing:-0.3px;">fast</span><span style="font-size:20px;font-weight:800;color:#111827;">bank</span><span style="font-size:15px;font-weight:400;color:#9ca3af;margin-left:5px;">Memories</span>
    </div>
    <div style="text-align:right;font-size:11px;color:#9ca3af;line-height:1.8;">
      <div style="font-weight:600;color:#6b7280;letter-spacing:0.5px;text-transform:uppercase;font-size:9px;">Session Closing Report</div>
      ${generatedBy ? `<div style="margin-top:2px;color:#6b7280;font-weight:500;">Generated by ${generatedBy}</div>` : ''}
      <div style="margin-top:1px;">${generatedAt}</div>
    </div>
  </div>

  <!-- SESSION META BAR -->
  <div style="background:#EDF2FA;padding:12px 48px;display:flex;gap:40px;justify-content:center;border-bottom:1px solid #e5e7eb;">
    ${[
      { label: 'Period',     value: session.period },
      { label: 'Account',    value: `${session.account}${session.accountNumber ? ' · ' + session.accountNumber : ''}` },
      { label: 'Currency',   value: session.currency ?? 'USD' },
      { label: 'Session ID', value: session.id },
    ]
      .map(
        (f) => `
      <div>
        <div style="font-size:9px;text-transform:uppercase;letter-spacing:1.5px;color:#9ca3af;font-weight:600;">${f.label}</div>
        <div style="font-size:13px;font-weight:600;color:#111827;margin-top:3px;">${f.value}</div>
      </div>`,
      )
      .join('')}
  </div>

  <!-- MAIN CONTENT -->
  <div style="padding:36px 48px;">

    <!-- PROBABILITY HERO -->
    <div style="display:flex;gap:40px;align-items:flex-start;margin-bottom:32px;padding-bottom:32px;border-bottom:1px solid #e5e7eb;">
      <div style="min-width:170px;">
        <div style="font-size:9px;text-transform:uppercase;letter-spacing:1.5px;color:#9ca3af;font-weight:600;margin-bottom:6px;">Close Probability</div>
        <div style="font-size:68px;font-weight:800;line-height:1;background:${GRADIENT};-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;">${currentPct}%</div>
        ${probabilityBar(narrator.stats.closeProbability)}
      </div>
      <div style="flex:1;padding-top:4px;">
        <div style="font-size:9px;text-transform:uppercase;letter-spacing:1.5px;color:#9ca3af;font-weight:600;margin-bottom:10px;">Brain Assessment</div>
        <p style="font-size:15px;line-height:1.65;color:#374151;font-style:italic;">"${narrator.headline}"</p>
      </div>
    </div>

    <!-- SESSION STATS -->
    <div class="no-break" style="display:flex;margin-bottom:32px;border:1px solid #e5e7eb;border-radius:12px;overflow:hidden;">
      ${statsHtml}
    </div>

    <!-- NARRATIVE -->
    <div style="margin-bottom:32px;">
      <div style="font-size:9px;text-transform:uppercase;letter-spacing:2px;color:${PURPLE};font-weight:700;margin-bottom:14px;">Session Narrative</div>
      ${narrativeParagraphs}
    </div>

    <!-- LEARNED THIS SESSION -->
    <div style="margin-bottom:32px;">
      <div style="font-size:9px;text-transform:uppercase;letter-spacing:2px;color:${PURPLE};font-weight:700;margin-bottom:4px;">What the Financial Brain Learned This Session</div>
      ${insightsHtml}
    </div>

    <!-- NEXT SESSION PROJECTION -->
    <div class="no-break" style="background:#EDF2FA;border:1.5px solid #e0d5ec;border-radius:12px;padding:28px 36px;margin-bottom:32px;">
      <div style="font-size:9px;text-transform:uppercase;letter-spacing:2px;color:${PURPLE};font-weight:700;margin-bottom:20px;">Next Session Projection</div>
      <div style="display:flex;gap:0;align-items:flex-start;">
        <div style="flex:1;text-align:center;">
          <div style="font-size:44px;font-weight:800;line-height:1;background:${GRADIENT};-webkit-background-clip:text;-webkit-text-fill-color:transparent;background-clip:text;">${nextPct}%</div>
          <div style="font-size:9px;text-transform:uppercase;letter-spacing:1px;color:#9ca3af;margin-top:7px;">Projected Close Probability</div>
        </div>
        <div style="width:1px;background:#e0d5ec;margin:0 28px;align-self:stretch;"></div>
        <div style="flex:1;text-align:center;">
          <div style="font-size:44px;font-weight:800;color:#6b21a8;line-height:1;">${deltaSign}${narrator.nextCloseDelta}%</div>
          <div style="font-size:9px;text-transform:uppercase;letter-spacing:1px;color:#9ca3af;margin-top:7px;">Improvement from Today</div>
        </div>
        <div style="width:1px;background:#e0d5ec;margin:0 28px;align-self:stretch;"></div>
        <div style="flex:1;text-align:center;">
          <div style="font-size:44px;font-weight:800;color:#6b21a8;line-height:1;">${narrator.sessionsToTarget}</div>
          <div style="font-size:9px;text-transform:uppercase;letter-spacing:1px;color:#9ca3af;margin-top:7px;">Sessions Until 95%+ Close Rate</div>
        </div>
      </div>
      <p style="font-size:11px;color:#9ca3af;font-style:italic;margin-top:18px;text-align:center;">
        Projection assumes all Memories recommendations with resolvability ≥ 50% are applied this session.
      </p>
    </div>

    <!-- DISCLAIMER -->
    <div class="no-break" style="background:#f9fafb;border-left:3px solid #e0d5ec;padding:16px 20px;border-radius:0 6px 6px 0;">
      <div style="font-size:9px;text-transform:uppercase;letter-spacing:1.5px;color:#9ca3af;font-weight:700;margin-bottom:6px;">Important Notice</div>
      <p style="font-size:11.5px;color:#6b7280;line-height:1.75;">
        This report was generated by FastBank Memories on ${generatedAt}.
        Close probability projections are based on historical reconciliation data for this account
        and are intended as operational guidance only. Values reflect the session state at the time
        of generation and do not constitute a final accounting decision. Always validate findings
        with your accounting team before making period-close or financial reporting decisions.
        FastBank Memories does not constitute financial, legal, or audit advice.
      </p>
    </div>

  </div>


</body>
</html>`;
}
